---
abstract: 'A simple monitoring and alarm system'
author:
  - 'WJIAN <cloveperl@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MColPro
no_index:
  directory:
    - t
    - inc
requires:
  Net::MySQL: 0.11
  YAML::XS: 0.38
version: 1.10
